// Code generated by protoc-gen-go.
// source: wen_Msg.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	wen_Msg.proto

It has these top-level messages:
	Friend
	AddFriendRequest
	SendMessage
	WMessage
	Groups
	User
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Gender int32

const (
	Gender_FEMALE Gender = 0
	Gender_MALE   Gender = 1
)

var Gender_name = map[int32]string{
	0: "FEMALE",
	1: "MALE",
}
var Gender_value = map[string]int32{
	"FEMALE": 0,
	"MALE":   1,
}

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}
func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}
func (x *Gender) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Gender_value, data, "Gender")
	if err != nil {
		return err
	}
	*x = Gender(value)
	return nil
}

type Mode int32

const (
	Mode_SYSTEM Mode = 0
	Mode_FILE   Mode = 1
	Mode_WAIT   Mode = 2
	Mode_AGREE  Mode = 3
	Mode_REFUSE Mode = 4
	Mode_TEXT   Mode = 5
)

var Mode_name = map[int32]string{
	0: "SYSTEM",
	1: "FILE",
	2: "WAIT",
	3: "AGREE",
	4: "REFUSE",
	5: "TEXT",
}
var Mode_value = map[string]int32{
	"SYSTEM": 0,
	"FILE":   1,
	"WAIT":   2,
	"AGREE":  3,
	"REFUSE": 4,
	"TEXT":   5,
}

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}
func (x Mode) String() string {
	return proto.EnumName(Mode_name, int32(x))
}
func (x *Mode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Mode_value, data, "Mode")
	if err != nil {
		return err
	}
	*x = Mode(value)
	return nil
}

// 好友
type Friend struct {
	Username         *string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Remark           *string `protobuf:"bytes,2,opt,name=remark" json:"remark,omitempty"`
	ProfilePhotoid   *int32  `protobuf:"varint,3,opt,name=profile_photoid" json:"profile_photoid,omitempty"`
	Online           *int32  `protobuf:"varint,4,opt,name=online" json:"online,omitempty"`
	Sex              *Gender `protobuf:"varint,5,opt,name=sex,enum=protocol.Gender" json:"sex,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Friend) Reset()         { *m = Friend{} }
func (m *Friend) String() string { return proto.CompactTextString(m) }
func (*Friend) ProtoMessage()    {}

func (m *Friend) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *Friend) GetRemark() string {
	if m != nil && m.Remark != nil {
		return *m.Remark
	}
	return ""
}

func (m *Friend) GetProfilePhotoid() int32 {
	if m != nil && m.ProfilePhotoid != nil {
		return *m.ProfilePhotoid
	}
	return 0
}

func (m *Friend) GetOnline() int32 {
	if m != nil && m.Online != nil {
		return *m.Online
	}
	return 0
}

func (m *Friend) GetSex() Gender {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return Gender_FEMALE
}

type AddFriendRequest struct {
	Sender           *string `protobuf:"bytes,1,req,name=sender" json:"sender,omitempty"`
	Modes            *Mode   `protobuf:"varint,2,req,name=modes,enum=protocol.Mode" json:"modes,omitempty"`
	Receiver         *string `protobuf:"bytes,3,req,name=receiver" json:"receiver,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AddFriendRequest) Reset()         { *m = AddFriendRequest{} }
func (m *AddFriendRequest) String() string { return proto.CompactTextString(m) }
func (*AddFriendRequest) ProtoMessage()    {}

func (m *AddFriendRequest) GetSender() string {
	if m != nil && m.Sender != nil {
		return *m.Sender
	}
	return ""
}

func (m *AddFriendRequest) GetModes() Mode {
	if m != nil && m.Modes != nil {
		return *m.Modes
	}
	return Mode_SYSTEM
}

func (m *AddFriendRequest) GetReceiver() string {
	if m != nil && m.Receiver != nil {
		return *m.Receiver
	}
	return ""
}

// 发送消息
type SendMessage struct {
	Receiver         *string `protobuf:"bytes,1,opt,name=receiver" json:"receiver,omitempty"`
	Type             *Mode   `protobuf:"varint,2,opt,name=type,enum=protocol.Mode" json:"type,omitempty"`
	Msg              *string `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
	File             []byte  `protobuf:"bytes,4,opt,name=file" json:"file,omitempty"`
	MsgTime          *int64  `protobuf:"varint,5,opt,name=msg_time" json:"msg_time,omitempty"`
	FileSize         *int64  `protobuf:"varint,6,opt,name=file_size" json:"file_size,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SendMessage) Reset()         { *m = SendMessage{} }
func (m *SendMessage) String() string { return proto.CompactTextString(m) }
func (*SendMessage) ProtoMessage()    {}

func (m *SendMessage) GetReceiver() string {
	if m != nil && m.Receiver != nil {
		return *m.Receiver
	}
	return ""
}

func (m *SendMessage) GetType() Mode {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Mode_SYSTEM
}

func (m *SendMessage) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func (m *SendMessage) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *SendMessage) GetMsgTime() int64 {
	if m != nil && m.MsgTime != nil {
		return *m.MsgTime
	}
	return 0
}

func (m *SendMessage) GetFileSize() int64 {
	if m != nil && m.FileSize != nil {
		return *m.FileSize
	}
	return 0
}

type WMessage struct {
	MsgType          *string           `protobuf:"bytes,1,req,name=msg_type" json:"msg_type,omitempty"`
	MsgTypeId        *int32            `protobuf:"varint,2,opt,name=msg_type_id" json:"msg_type_id,omitempty"`
	System           *string           `protobuf:"bytes,3,opt,name=system" json:"system,omitempty"`
	SendMsg          *SendMessage      `protobuf:"bytes,4,opt,name=send_msg" json:"send_msg,omitempty"`
	UserInfo         *User             `protobuf:"bytes,5,opt,name=user_info" json:"user_info,omitempty"`
	StataCode        *int32            `protobuf:"varint,6,opt,name=stata_code" json:"stata_code,omitempty"`
	AddFriend        *AddFriendRequest `protobuf:"bytes,7,opt,name=add_friend" json:"add_friend,omitempty"`
	Friends          []*Friend         `protobuf:"bytes,8,rep,name=friends" json:"friends,omitempty"`
	MsgTime          *int64            `protobuf:"varint,9,opt,name=msg_time" json:"msg_time,omitempty"`
	Group            *Groups           `protobuf:"bytes,10,opt,name=group" json:"group,omitempty"`
	Devices          *string           `protobuf:"bytes,11,opt,name=devices" json:"devices,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *WMessage) Reset()         { *m = WMessage{} }
func (m *WMessage) String() string { return proto.CompactTextString(m) }
func (*WMessage) ProtoMessage()    {}

func (m *WMessage) GetMsgType() string {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return ""
}

func (m *WMessage) GetMsgTypeId() int32 {
	if m != nil && m.MsgTypeId != nil {
		return *m.MsgTypeId
	}
	return 0
}

func (m *WMessage) GetSystem() string {
	if m != nil && m.System != nil {
		return *m.System
	}
	return ""
}

func (m *WMessage) GetSendMsg() *SendMessage {
	if m != nil {
		return m.SendMsg
	}
	return nil
}

func (m *WMessage) GetUserInfo() *User {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *WMessage) GetStataCode() int32 {
	if m != nil && m.StataCode != nil {
		return *m.StataCode
	}
	return 0
}

func (m *WMessage) GetAddFriend() *AddFriendRequest {
	if m != nil {
		return m.AddFriend
	}
	return nil
}

func (m *WMessage) GetFriends() []*Friend {
	if m != nil {
		return m.Friends
	}
	return nil
}

func (m *WMessage) GetMsgTime() int64 {
	if m != nil && m.MsgTime != nil {
		return *m.MsgTime
	}
	return 0
}

func (m *WMessage) GetGroup() *Groups {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *WMessage) GetDevices() string {
	if m != nil && m.Devices != nil {
		return *m.Devices
	}
	return ""
}

type Groups struct {
	Id               *string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	GroupName        *string   `protobuf:"bytes,2,opt,name=group_name" json:"group_name,omitempty"`
	Owner            *string   `protobuf:"bytes,3,opt,name=owner" json:"owner,omitempty"`
	Description      *string   `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	GroupMember      []*Friend `protobuf:"bytes,5,rep,name=group_member" json:"group_member,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Groups) Reset()         { *m = Groups{} }
func (m *Groups) String() string { return proto.CompactTextString(m) }
func (*Groups) ProtoMessage()    {}

func (m *Groups) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Groups) GetGroupName() string {
	if m != nil && m.GroupName != nil {
		return *m.GroupName
	}
	return ""
}

func (m *Groups) GetOwner() string {
	if m != nil && m.Owner != nil {
		return *m.Owner
	}
	return ""
}

func (m *Groups) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *Groups) GetGroupMember() []*Friend {
	if m != nil {
		return m.GroupMember
	}
	return nil
}

type User struct {
	Id               *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Username         *string `protobuf:"bytes,2,req,name=username" json:"username,omitempty"`
	Password         *string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	NewPassword      *string `protobuf:"bytes,4,opt,name=new_password" json:"new_password,omitempty"`
	Sex              *Gender `protobuf:"varint,5,opt,name=sex,enum=protocol.Gender,def=1" json:"sex,omitempty"`
	Age              *int32  `protobuf:"zigzag32,6,opt,name=age" json:"age,omitempty"`
	Phone            *string `protobuf:"bytes,7,opt,name=phone" json:"phone,omitempty"`
	RealName         *string `protobuf:"bytes,8,opt,name=real_name" json:"real_name,omitempty"`
	ProfilePhotoid   *int32  `protobuf:"varint,9,opt,name=profile_photoid" json:"profile_photoid,omitempty"`
	ChatGroundid     *int32  `protobuf:"varint,10,opt,name=chat_groundid" json:"chat_groundid,omitempty"`
	Email            *string `protobuf:"bytes,11,opt,name=email" json:"email,omitempty"`
	Notice           *string `protobuf:"bytes,12,opt,name=notice" json:"notice,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}

const Default_User_Sex Gender = Gender_MALE

func (m *User) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *User) GetNewPassword() string {
	if m != nil && m.NewPassword != nil {
		return *m.NewPassword
	}
	return ""
}

func (m *User) GetSex() Gender {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return Default_User_Sex
}

func (m *User) GetAge() int32 {
	if m != nil && m.Age != nil {
		return *m.Age
	}
	return 0
}

func (m *User) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *User) GetRealName() string {
	if m != nil && m.RealName != nil {
		return *m.RealName
	}
	return ""
}

func (m *User) GetProfilePhotoid() int32 {
	if m != nil && m.ProfilePhotoid != nil {
		return *m.ProfilePhotoid
	}
	return 0
}

func (m *User) GetChatGroundid() int32 {
	if m != nil && m.ChatGroundid != nil {
		return *m.ChatGroundid
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *User) GetNotice() string {
	if m != nil && m.Notice != nil {
		return *m.Notice
	}
	return ""
}

func init() {
	proto.RegisterEnum("protocol.Gender", Gender_name, Gender_value)
	proto.RegisterEnum("protocol.Mode", Mode_name, Mode_value)
}
